<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions  
    targetNamespace="http://www.anpr.interno.it/ANPR_CIE_Integration/ServerCIEOnline/Service"
    
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    
    xmlns:datatype="http://www.anpr.interno.it/ANPR_CIE_Integration/ServerCIEOnline/Datatypes"
    xmlns:service="http://www.anpr.interno.it/ANPR_CIE_Integration/ServerCIEOnline/Service">
    
    
    <!-- section: TYPES -->
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.anpr.interno.it/ANPR_CIE_Integration/ServerCIEOnline/Datatypes" schemaLocation="ServerCIEOnline_Datatype.xsd"/>
        </xsd:schema>
    </wsdl:types>
    
    <!-- section: MESSAGE -->    
    <wsdl:message name="N031Request">
        <wsdl:part name="request" type="datatype:N031Request"/>
    </wsdl:message>
    
    <wsdl:message name="N031Response">
        <wsdl:part name="respose" type="datatype:N031Response"/>
    </wsdl:message>
    
    <wsdl:portType name="ServerCIEOnlinePortType">
        <wsdl:operation name="NotificaSubentro">
            <wsdl:input message="service:N031Request"/>
            <wsdl:output message="service:N031Response"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ServerCIEOnlineBinding" type="service:ServerCIEOnlinePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="NotificaSubentro">
            <soap:operation soapAction="http://SSCE/NotificaSubentro"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ServerCIEOnline">
        <wsdl:port name="ServerCIEOnlinePort" binding="service:ServerCIEOnlineBinding">
            <soap:address location="http://localhost:8080/ANPRNotificaSubentroService"/>
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>